name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-15] # , ubuntu-latest
        type: [Windows, macOS, Android, iOS] # , Linux
        exclude:
          - os: macos-15
            type: Windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v5

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Installeer MAUI workloads
        run: dotnet workload install maui --ignore-failed-sources
        if: ${{ matrix.os != 'ubuntu-latest' }}

      - name: Installeer Linux MAUI workloads
        run: dotnet workload install maui-android --ignore-failed-sources
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Bouw de Android applicatie
        run: dotnet build --configuration Release -f net8.0-android Grocery.App/Grocery.App.csproj --no-restore
        if: ${{ always() && matrix.type == 'Android' }}
      - name: Voer unit tests uit voor Android
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
        if: ${{ success() && matrix.type == 'Android' }}
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        if: false
        with:
          name: GroceryApp-Android
          path: ./Grocery.App/bin/Release/net8.0-android/*Signed.a*

      - name: Bouw de iOS applicatie
        run: dotnet build --configuration Release -f net8.0-ios Grocery.App/Grocery.App.csproj --no-restore
        if: ${{ always() && matrix.type == 'iOS' }}
      - name: Voer unit tests uit voor iOS
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
        if: ${{ success() && matrix.type == 'iOS' }}
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        if: false
        with:
          name: GroceryApp-iOS
          path: ./Grocery.App/bin/Release/net8.0-ios/**/*.app/

      - name: Bouw de Windows applicatie
        run: dotnet build --configuration Release -f net8.0-windows10.0.19041.0 Grocery.App/Grocery.App.csproj /p:RuntimeIdentifierOverride=win-x64 /p:EnableWindowsTargeting=true
        if: ${{ always() && matrix.type == 'Windows' && runner.os != 'macOS' }}
      - name: Voer unit tests uit voor Windows
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
        if: ${{ success() && matrix.type == 'Windows' && runner.os != 'macOS' }}
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        if: false
        with:
          name: GroceryApp-Windows
          path: ./Grocery.App/bin/Release/net8.0-windows*/**/*.msix

      - name: Bouw de macOS applicatie
        run: dotnet build --configuration Release -f net8.0-maccatalyst Grocery.App/Grocery.App.csproj /p:RuntimeIdentifierOverride=maccatalyst-x64
        if: ${{ always() && matrix.type == 'macOS' }}
      - name: Voer unit tests uit voor macOS
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
        if: ${{ success() && matrix.type == 'macOS' }}
      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v4
        if: false
        with:
          name: GroceryApp-macOS
          path: ./Grocery.App/bin/Release/net8.0-maccatalyst/**/*.app/

      - name: Bouw de Linux applicatie (Doesn't work)
        run: dotnet build --configuration Release -f net8.0-linux Grocery.App/Grocery.App.csproj
        if: ${{ always() && matrix.type == 'Linux' }}
      - name: Voer unit tests uit voor Linux (Doesn't work)
        run: dotnet test --configuration Release --no-restore --no-restore --no-build --verbosity normal
        if: ${{ success() && matrix.type == 'Linux' }}
      - name: Upload Linux Artifact (Doesn't work)
        uses: actions/upload-artifact@v4
        if: false
        with:
          name: GroceryApp-Linux
          path: ./Grocery.App/bin/Release/net8.0-linux/**/*
