name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - dev
      - hotfix/actions-file
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-15] # , ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Haal de repository op
        uses: actions/checkout@v5

      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Installeer MAUI workloads
        run: dotnet workload install maui --ignore-failed-sources
        if: ${{ matrix.os != 'ubuntu-latest' }}

      - name: Installeer Linux MAUI workloads
        run: dotnet workload install maui-android --ignore-failed-sources
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Herstel afhankelijkheden
        run: dotnet restore

      - name: Bouw de Windows applicatie
        run: dotnet build --configuration Release -f net8.0-windows10.0.19041.0 Grocery.App/Grocery.App.csproj /p:RuntimeIdentifierOverride=win-x64 /p:EnableWindowsTargeting=true
        if: ${{ always() && runner.os != 'macOS' }}
      - name: Voer unit tests uit voor Windows
        run: dotnet test --configuration Release TestCore/TestCore.csproj --no-restore --verbosity normal
        if: ${{ success() && runner.os != 'macOS' }}
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() && runner.os != 'macOS' }}
        with:
          name: GroceryApp-Windows--From-${{ runner.os }}
          path: |
            ./Grocery.App/bin/Release/net8.0-windows10.0.19041.0/win10-x64/**/*

      - name: Bouw de macOS applicatie
        run: dotnet build --configuration Release -f net8.0-maccatalyst Grocery.App/Grocery.App.csproj /p:RuntimeIdentifierOverride=maccatalyst-x64
        if: ${{ always() }}
      - name: Voer unit tests uit voor macOS
        run: dotnet test --configuration Release TestCore/TestCore.csproj --no-restore --verbosity normal
        if: ${{ success() }}
      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() && runner.os == 'macOS' }}
        with:
          name: GroceryApp-macOS--From-${{ runner.os }}
          path: ./Grocery.App/bin/Release/net8.0-maccatalyst/maccatalyst-x64/**/*.app/

      - name: Bouw de Android applicatie
        run: dotnet build --configuration Release -f net8.0-android Grocery.App/Grocery.App.csproj
        if: ${{ always() }}
      - name: Voer unit tests uit voor Android
        run: dotnet test --configuration Release TestCore/TestCore.csproj --no-restore --verbosity normal
        if: ${{ success() }}
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: GroceryApp-Android--From-${{ runner.os }}
          path: ./Grocery.App/bin/Release/net8.0-android/**/*Signed.a*

      - name: Bouw de iOS applicatie
        run: dotnet build --configuration Release -f net8.0-ios Grocery.App/Grocery.App.csproj
        if: ${{ always() }}
      - name: Voer unit tests uit voor iOS
        run: dotnet test --configuration Release TestCore/TestCore.csproj --no-restore --verbosity normal
        if: ${{ success() }}
      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        if: ${{ success() && runner.os == 'macOS' }}
        with:
          name: GroceryApp-iOS--From-${{ runner.os }}
          path: ./Grocery.App/bin/Release/net8.0-ios/**/*.app/

      # Bouwen voor Linux is niet mogelijk met MAUI. Dit kan wel met Avalonia
      #- name: Bouw de Linux applicatie
      #  run: dotnet build --configuration Release -f net8.0-linux Grocery.App/Grocery.App.csproj
      #  if: ${{ always() }}
      #- name: Voer unit tests uit voor Linux
      #  run: dotnet test --configuration Release TestCore/TestCore.csproj --no-restore --verbosity normal
      #  if: ${{ success() }}
      #- name: Upload Linux Artifact (Doesn't work)
      #  uses: actions/upload-artifact@v4
      #  if: ${{ success() }}
      #  with:
      #    name: GroceryApp-Linux--From-${{ runner.os }}
      #    path: ./Grocery.App/bin/Release/net8.0-linux/**/Grocery.App*
